#pragma once
#include <vector>
#include <sstream>
#include <ostream>
#include <set>
#include <iterator>
#include "stdxx/memory.hxx"
#include "stdxx/algorithm.hxx"
#include "stdxx/iterator.hxx"
#include "stdxx/io.hxx"
#include "stdxx/args/args.hxx"
#include "stdxx/args/optiona_description.hxx"
#include "stdxx/args/option.hxx"
#include "stdxx/args/option_flag.hxx"
#include "stdxx/args/option_value.hxx"
#include "stdxx/args/option_list.hxx"
